language: python

services:
  - docker

install:
  - bash activate

script:
  - znake static
  - znake test.u16
  - znake test.u18
  - znake systest.u16
  - znake systest.u18
  - znake debtest.u16
  - znake debtest.u18
