language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install texlive-base texlive-latex-extra

install:
  - bash activate

script:
  - znake static
  - znake test.u16
  - znake test.u18
